version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      FLASK_APP: app.py
    container_name: backend-container
    volumes:
      - "/mnt/d/04\ -\ Cursos/01\ -\ RocketSeat/GoStack\ 11/GoStack\ Bootcamp\ 11:/app/courses/GoStack"
